### PR TITLE
Tms/customers endpoint #3

### LINKED ISSUE #3: Customers record endpoint

### PR DESCRIPTION
**Pull request by tmikeschu**
@Dpalazzari similar to the merchants branch we worked on, this is ready to go once we figure out how to handle case-insensitivity and time queries.

- Adds API endpoints for Customers: index, show, find, find_all, and random.
- Adds request helper for those lengthy attribute expectations.
- Adds class method for models to randomly select a record.

Needs in-depth review

Closes #3 

@sallymacnicholas

### CODE REVIEW

**Comment by saltybigmac** [comment]
This looks like a great start to me. I'm noticing some spacing is off in some places so just make sure you do a final run through for that at the end of the project or as you see it in files.

Only question, where does the #random method live for the Customer model?

**Comment by Dpalazzari** [comment]
Where are you seeing the spacing problems? @sallymacnicholas 

And to reply to your last question, that method lives in the application record file. We are using the same method in multiple controllers so we put it on the app record file.

*update: We looked at the spacing issues and thats just a formatting issue on github. On our local machines, the spacing is fine. @sallymacnicholas

**Comment by tmikeschu** [comment]
@Dpalazzari , @sallymacnicholas : I went through and made the necessary data type changes for case insensitivity and timestamp precision.

- Add API endpoints for customers: index, show, find_all, find, and random.

All tests passing.

Needs in-depth review

Closes #3

**Comment by Dpalazzari** [comment]
I approve this PR because I sat right next to @tmikeschu and worked on it with him.

👍

**Pull request merged**
